### ISSUE TITLE
[BUG] Added game doesn't show up in deck stats

### ISSUE THREAD

**Issue by GARLICDOG** [sirajch/agotstats#20]
Hey,

I manually added a game to one of my decks, I only edited the the deck name, enemy faction, agenda, notes and outcome of the game and left the other options as they are. After clicking "add game" and checking the deck stats I could not find the game in there. I repeated the process 2 more times (in a couple of minutes, then about an hour later) but the game didn't show up either time.

I am not sure if this is a bug or I am doing something wrong (I already added 5 games without a problem to the deck, this was the first time it happened, coincidentally right after I edited the notes on one of the games).

Account name: Zsolt
Deck: TARGRUSH
Game against: Greyjoy-Reddoor
Date: 2018.08.31.

**Comment by sirajch** [comment]
I found the error when inserting into DB. Your notice contains string "'" and that force the error when trying to save into DB. I found your game record in my log, so I insert it into DB by myself. Check it, if it's fine now.

Thanks for reporting this.

**Comment by GARLICDOG** [comment]
Thank you very much for the fast answer, it did help, the game is added to the deck now and I added a new game recently it also appeared. Thanks!

**Comment by sirajch** [comment]
Nice. Thx.
