### ISSUE TITLE
Cannot update import

### ISSUE THREAD

**Issue by mrdavnor** [sirajch/agotstats#43]
My account hasn't updated since September. I can't delete the data or reimport as it keeps asking me to login again. If I cancel it I get an error page - "

  Don't have access to this page (incorrect login or password)

    Try to close whole browser and log in again
    If you forgot password ask me about new one

"

I have tried changing my password, clearing cookies/cache, and on numerous days, and on both Firefox and Chrome.

**Comment by sirajch** [comment]
I will try it tomorrow. Maybe I will change your password. We will see thanks for reporting this

**Comment by sirajch** [comment]
Fixed. You should have an email from me. Thx
